name: PostgreSQL / Postgis / Pgrouting
description: |
  pgRouting extends the PostGIS / PostgreSQL geospatial database to provide geospatial routing functionality.
version: 9.4-2.1-2.1-rancher1
category: Database
maintainer: "Thomas Pham <thomas.pham@ithings.ch>"
minimum_rancher_version: v1.1.3
license:
projectURL: https://github.com/Starefossen/docker-pgrouting
