name: Yahoo Kafka Manager
description: |
  A tool for managing Apache Kafka cluster, topics, stats, ...
version: 1.3.1.6-rancher1
category: Clustering
maintainer: "Thomas Pham <thomas.pham@ithings.ch>"
minimum_rancher_version: v1.1.3
license: 
projectURL: https://github.com/yahoo/kafka-manager
